spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.time_zone: UTC # 배치에서 LocalDateTime → Instant 변환 시 UTC 기준으로 계산
  batch:
    job:
      enabled: false # 애플리케이션 시작 시 배치 작업 자동 실행 방지
    jdbc:
      initialize-schema: always # Spring Batch 관련 테이블 자동 생성

logging:
  level:
    com.twogether.deokhugam: info
    org.hibernate.SQL: info
  file:
    path: /app/logs
    name: application

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,prometheus
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false

info:
  name: Deokhugam
  version: 0.1.0-dev
  java:
    version: 17
  spring-boot:
    version: 3.5.3
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}


#Spring Batch 설정
batch:
  popular-book-ranking:
    enabled: true
    cron: "0 */5 * * * *"

  popular-review-ranking:
    enabled: true
    cron: "0 */5 * * * *"

  power-user-ranking:
    enabled: true
    cron: "0 */5 * * * *"
  notification-cleanup:
    enabled: true
    cron: "0 */15 * * * *"