spring:
  profiles:
    active: dev
  application:
    name: Deokhugam
  config:
    import: optional:dotenv:.env
  #Spring Batch 설정
  batch:
    job:
      enabled: false # 애플리케이션 시작 시 배치 작업 자동 실행 방지
    jdbc:
      initialize-schema: always # Spring Batch 관련 테이블 자동 생성

#NaverBookAPI 접속 정보
naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

#env 환경설정값 Actuator 모니터링 옵션(false 권장)
management:
  info:
    env:
      enabled: false