spring:
  application:
    name: deokhugam
  profiles:
    active: dev
  config:
    import: optional:dotenv:.env
  #Spring Batch 설정
  batch:
    job:
      enabled: false # 애플리케이션 시작 시 배치 작업 자동 실행 방지
    jdbc:
      initialize-schema: always # Spring Batch 관련 테이블 자동 생성
  datasource:
    driver-class-name: org.postgresql.Driver

# 공통 로깅 설정
logging:
  level:
    root: info

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
